### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by hzhao1997** [MoritzKappel/HF-NHMT#1]
Thanks for your great work! I try to apply your code on my data and run ./scripts/generate_dataset.py  to generate training inputs and labels. But when I run ./scripts/train.py and I got this error. Could you give me some advice : ）

File "./scripts/train.py", line 206, in <module>
    main()
  File "./scripts/train.py", line 88, in main
    images, poses, dynamics, segmentations, structure = utils.castDataTuple(dataset[i], tensor_type, unsqueeze=False)
  File "/home/zhao/HF-NHMT/core/Datasets.py", line 102, in __getitem__
    sample = self.loadSample(idx)
  File "/home/zhao/HF-NHMT/core/Datasets.py", line 83, in loadSample
    edges = clothes_mask * edges
ValueError: operands could not be broadcast together with shapes (512,512,18) (2,512,512)

**Comment by MoritzKappel** [comment]
This is a weird error. In theory, the first tensor is supposed to be a binary mask of shape (1, H, W). In your case, the dimensions match a transposed version of the original segmentation map,  indicating that the masking operation failed.
Could you kindly send me a subset of your training data (a single sample should be enough) and a copy of your configuration file, so I can recreate the problem in my debugger?

**Comment by hzhao1997** [comment]
> This is a weird error. In theory, the first tensor is supposed to be a binary mask of shape (1, H, W). In your case, the dimensions match a transposed version of the original segmentation map, indicating that the masking operation failed.
> Could you kindly send me a subset of your training data (a single sample should be enough) and a copy of your configuration file, so I can recreate the problem in my debugger?

Thanks for you reply. I solved this porblem by generating data again and now I can run ./scripts/train.py successfuly.  I train the generated data for 50 epochs but I get empty output image. There is still something wrong with my data generation.

This is the output file: 
[Body2D_2006_342.zip](https://github.com/MoritzKappel/HF-NHMT/files/6922424/Body2D_2006_342.zip)

ps: I uncomment the 346 line `gr.run()` for my headless server. Is it the reason for my failure training?

**Comment by MoritzKappel** [comment]
Thanks for the output data. The segmentation networks seems to work fine. One potential reason for the rendering network to produce empty images is erroneous (i.e. empty) input tensors. However, even in that case, you should be able to see parts of the background frame, if available. Commenting out _gr.run()_ is valid, and should just result in the standard parameters used for all experiments shown in out paper.

If you could provide me with a small subset of your dataset (e.g. via email: kappel@cg.cs.tu-bs.de), as well as the config file used for training/inference, I can try to reproduce and fix the problem.

**Comment by hzhao1997** [comment]
Sorry for late response and I have already sent the data and config file to your email. Thanks for your debugging : )

**Comment by MoritzKappel** [comment]
Thanks for sharing the data. I just tested pertained models on your dataset, and got valid result images (see attached example). For this reason, I must assume that the error happens during training. I will start a new training run on your data and see if I can spot any issues. Did you get non-empty images in your tensor board training visualization?
![00016](https://user-images.githubusercontent.com/75040099/128714499-dbde3628-e12f-4870-81dc-d98065eef7fe.png)

**Comment by hzhao1997** [comment]
I try to visual it like this but I am not sure whether it is normal.
![Screenshot from 2021-08-09 22-35-41](https://user-images.githubusercontent.com/32841739/128724525-61797eb2-a194-4fa6-a95a-06d7bc654209.png)
![Screenshot from 2021-08-09 22-36-50](https://user-images.githubusercontent.com/32841739/128724532-3f2bca49-cc4a-4d67-ad75-12da22b0ee48.png)

**Comment by hzhao1997** [comment]
I try to visualize it like this but I am not sure whether it is normal.
![Screenshot from 2021-08-09 22-35-41](https://user-images.githubusercontent.com/32841739/128725103-a5a490ad-d65d-42fd-9504-f038a59a3df7.png)
![Screenshot from 2021-08-09 22-36-50](https://user-images.githubusercontent.com/32841739/128725115-3687e0ce-8b12-4465-9b0d-1cfef25053bb.png)

**Comment by MoritzKappel** [comment]
I think I found the error. Due to a zero division in training data generation, you get NaNs in the structure annotation, causing the foreground network to output a zero image. In combination with the black background frame, this results in an empty image. Could you kindly try to replace line 487 in _generate_dataset.py_:
`confidence = np.expand_dims(np.amax(activations, axis=0) / cv2.GaussianBlur(self.image_gray, ksize=(7, 7), sigmaX=2.0), axis=2)`
with
`confidence = np.expand_dims(np.amax(activations, axis=0) / (cv2.GaussianBlur(self.image_gray, ksize=(7, 7), sigmaX=2.0) + 1e-6), axis=2)`
and check if it fixes the problem?
You will need rename or remove the old structure annotations in your dataset directory and re-run the data generation script. This should produce a structure tensor visualisation video similar to the results shown in the paper, and training should run as intended.

**Comment by hzhao1997** [comment]
Thanks for your kind help and now it works : )
