### ISSUE TITLE
Gpu memory cost

### ISSUE THREAD

**Issue by hzhao1997** [MoritzKappel/HF-NHMT#2]
Does the default batch size equal 1？ If so, is there any solutions to lower the memory cost with no more than 11GB ？: )

**Comment by MoritzKappel** [comment]
Hi, the default batch size is 1 and should not be changed, as images are processed sequentially.
To reduce VRAM requirements, you can train each network component individually  (i.e. run the training script 3 times) by deactivating the other components in the config file.

**Comment by hzhao1997** [comment]
Thanks for your quick reply and I will try it.
