### ISSUE TITLE
Pertained models

### ISSUE THREAD

**Issue by qo4on** [MoritzKappel/HF-NHMT#3]
Hi!
Did you release pertained models? If not could you tell how much time did it take to train and what hardware?

**Comment by MoritzKappel** [comment]
Hi! So far, we did not release any pertained models. Depending on the sequence, training took about 3-4 days on a single Titan RTX, and ~20% less on a Quadro RTX 8000 GPU. Also, I recommend loading data from a fast m.2 SSD (we used a Samsung 970 EVO+).
